### ISSUE TITLE
error when running python Run.py

### ISSUE THREAD

**Issue by HappyDay-design** [alinaciuysal/SimplaPlatoon#2]
Hello

I followed other steps
But when I run python Run.py, it had errors

(Hung3.7) D:\Download\SimplaPlatoon-master>C:/Users/PKNU/anaconda3/envs/Hung3.7/python.exe d:/Download/SimplaPlatoon-master/Run.py
Traceback (most recent call last):
  File "d:/Download/SimplaPlatoon-master/Run.py", line 1, in <module>
    import app.Initiator as Initiator
  File "d:\Download\SimplaPlatoon-master\app\Initiator.py", line 4, in <module>
    from app.streaming import KafkaConnector
  File "d:\Download\SimplaPlatoon-master\app\streaming\KafkaConnector.py", line 1, in <module>
    from kafka import KafkaConsumer
  File "C:\Users\PKNU\anaconda3\envs\Hung3.7\lib\site-packages\kafka\__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "C:\Users\PKNU\anaconda3\envs\Hung3.7\lib\site-packages\kafka\producer\__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "C:\Users\PKNU\anaconda3\envs\Hung3.7\lib\site-packages\kafka\producer\simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                                  ^
SyntaxError: invalid syntax

**Comment by alinaciuysal** [comment]
Hi, 
Project was developed using python2.7

**Comment by HappyDay-design** [comment]
> Hi, Project was developed using python2.7

Thank you for your quick reply
